# Esplorazione dell'OCEL

In [1]:
import pandas as pd
import pm4py

from ocpm_partial_order.config import (
    MAIN_DATASET_DB,
    TABLES_DIR,
)
from ocpm_partial_order.io.ocel_loader import (
    load_ocel2_sqlite,
)

TABLES_DIR.mkdir(parents=True, exist_ok=True)

ocel = load_ocel2_sqlite(MAIN_DATASET_DB)

print("Dataset:", MAIN_DATASET_DB.name)
print(ocel)

============================================================

  Welcome to PM4Py — Community Version
  Open-Source License (AGPL v3)

  📚 Docs & Examples:
     https://processintelligence.solutions/pm4py

  ⚖️  License: AGPL v3 — Commercial use requires open-sourcing your application.
     Business use without open-sourcing? A commercial license is available:
     https://processintelligence.solutions/pm4py#licensing

============================================================

Dataset: order_management.sqlite
Object-Centric Event Log (number of events: 21008, number of objects: 10825, number of activities: 11, number of object types: 5, events-objects relationships: 143463)
Activities occurrences: Counter({'pick item': 7659, 'place order': 2000, 'confirm order': 2000, 'pay order': 2000, 'item out of stock': 1544, 'reorder item': 1544, 'create package': 1128, 'send package': 1128, 'package delivered': 1128, 'payment reminder': 566, 'failed delivery': 311})
Object types occurrences (number of objects): Counter({'items': 7659, 'orders': 2000, 'packages': 1128, 'products': 20, 'employees': 18})
Unique activities per object type: Counter({'items': 11, 'products': 11, 'employees': 8, 'orders': 4, 'packages': 4})
Please use <THIS>.get_extended_table() to get a dataframe representation of the events related to the objects.

In [2]:
print("Colonne eventi:")
print(ocel.events.columns.tolist())

print("\nColonne oggetti:")
print(ocel.objects.columns.tolist())

print("\nColonne relazioni evento-oggetto:")
print(ocel.relations.columns.tolist())

Colonne eventi:
['ocel:eid', 'ocel:timestamp', 'ocel:activity']

Colonne oggetti:
['ocel:oid', 'role', 'weight', 'price', 'ocel:type']

Colonne relazioni evento-oggetto:
['ocel:eid', 'ocel:oid', 'ocel:qualifier', 'ocel:activity', 'ocel:timestamp', 'ocel:type']

In [3]:
print("EVENTI")
display(ocel.events.head(10))

print("OGGETTI")
display(ocel.objects.head(10))

print("RELAZIONI EVENTO-OGGETTO")
display(ocel.relations.head(10))

EVENTI

                ocel:eid            ocel:timestamp      ocel:activity
0         place_o-990001 2023-04-03 10:08:18+00:00        place order
0          pick_i-880003 2023-04-03 11:21:49+00:00          pick item
1         place_o-990002 2023-04-03 14:36:55+00:00        place order
2         place_o-990003 2023-04-03 21:31:23+00:00        place order
1          pick_i-880001 2023-04-04 07:50:21+00:00          pick item
2          pick_i-880006 2023-04-04 08:01:31+00:00          pick item
3         place_o-990004 2023-04-04 10:30:50+00:00        place order
3          pick_i-880020 2023-04-04 13:08:41+00:00          pick item
0  out_of_stock_i-880016 2023-04-04 13:42:47+00:00  item out of stock
4          pick_i-880015 2023-04-04 13:54:23+00:00          pick item

OGGETTI

                ocel:oid      role  weight  price  ocel:type
0      Wil van der Aalst     Sales     NaN    NaN  employees
1  Christine von Dobbert     Sales     NaN    NaN  employees
2       Jan Niklas Adams     Sales     NaN    NaN  employees
3          Mara Nitschke     Sales     NaN    NaN  employees
4           Istvan Koren     Sales     NaN    NaN  employees
5       Alessandro Berti  Shipment     NaN    NaN  employees
6  Eduardo Goulart Rocha  Shipment     NaN    NaN  employees
7           Majid Rafiei  Shipment     NaN    NaN  employees
8             Viki Peeva  Shipment     NaN    NaN  employees
9           Yisong Zhang  Shipment     NaN    NaN  employees

RELAZIONI EVENTO-OGGETTO

,ocel:eid,ocel:oid,ocel:qualifier,ocel:activity,ocel:timestamp,ocel:type
32973,place_o-990001,Echo,product,place order,2023-04-03 10:08:18+00:00,products
32974,place_o-990001,i-880001,item,place order,2023-04-03 10:08:18+00:00,items
32975,place_o-990001,i-880002,item,place order,2023-04-03 10:08:18+00:00,items
32976,place_o-990001,i-880003,item,place order,2023-04-03 10:08:18+00:00,items
32977,place_o-990001,iPhone 11 Pro,product,place order,2023-04-03 10:08:18+00:00,products
32978,place_o-990001,o-990001,order,place order,2023-04-03 10:08:18+00:00,orders
93215,pick_i-880003,Leah Tacke genannt Unterberg,employee,pick item,2023-04-03 11:21:49+00:00,employees
93216,pick_i-880003,i-880003,item,pick item,2023-04-03 11:21:49+00:00,items
93217,pick_i-880003,iPhone 11 Pro,product,pick item,2023-04-03 11:21:49+00:00,products
32980,place_o-990002,Kindle Paperwhite,product,place order,2023-04-03 14:36:55+00:00,products

In [4]:
required_event_columns = {
    "ocel:eid",
    "ocel:activity",
    "ocel:timestamp",
}

required_object_columns = {
    "ocel:oid",
    "ocel:type",
}

required_relation_columns = {
    "ocel:eid",
    "ocel:oid",
    "ocel:type",
}

missing_event_columns = (
    required_event_columns - set(ocel.events.columns)
)
missing_object_columns = (
    required_object_columns - set(ocel.objects.columns)
)
missing_relation_columns = (
    required_relation_columns - set(ocel.relations.columns)
)

print("Colonne mancanti negli eventi:", missing_event_columns)
print("Colonne mancanti negli oggetti:", missing_object_columns)
print("Colonne mancanti nelle relazioni:", missing_relation_columns)

Colonne mancanti negli eventi: set()
Colonne mancanti negli oggetti: set()
Colonne mancanti nelle relazioni: set()

In [5]:
general_summary = pd.DataFrame(
    [
        {
            "dataset": "Order Management",
            "events": len(ocel.events),
            "objects": len(ocel.objects),
            "event_object_relations": len(ocel.relations),
            "event_types": ocel.events[
                "ocel:activity"
            ].nunique(),
            "object_types": ocel.objects[
                "ocel:type"
            ].nunique(),
        }
    ]
)

display(general_summary)

,dataset,events,objects,event_object_relations,event_types,object_types
0,Order Management,21008,10825,143463,11,5

In [6]:
general_summary.to_csv(
    TABLES_DIR / "order_management_general_summary.csv",
    index=False,
)

In [7]:
event_type_counts = (
    ocel.events["ocel:activity"]
    .value_counts()
    .rename_axis("activity")
    .reset_index(name="event_count")
)

display(event_type_counts)

             activity  event_count
0           pick item         7659
1         place order         2000
2       confirm order         2000
3           pay order         2000
4   item out of stock         1544
5        reorder item         1544
6      create package         1128
7        send package         1128
8   package delivered         1128
9    payment reminder          566
10    failed delivery          311

In [8]:
event_type_counts.to_csv(
    TABLES_DIR / "order_management_event_types.csv",
    index=False,
)

In [9]:
object_type_counts = (
    ocel.objects["ocel:type"]
    .value_counts()
    .rename_axis("object_type")
    .reset_index(name="count")
)

display(object_type_counts)

  object_type  count
0       items   7659
1      orders   2000
2    packages   1128
3    products     20
4   employees     18

In [10]:
object_type_counts.to_csv(
    TABLES_DIR / "order_management_object_types.csv",
    index=False,
)

In [11]:
objects_per_event = (
    ocel.relations
    .groupby("ocel:eid")["ocel:oid"]
    .nunique()
    .rename("object_count")
    .sort_values(ascending=False)
)

display(objects_per_event.head(20))

ocel:eid
send_p-660903        37
deliver_p-660903     36
fail_p-660903_244    36
create_p-660903      36
send_p-660024        35
deliver_p-660024     34
create_p-660024      34
send_p-660979        34
deliver_p-660979     33
send_p-660379        33
send_p-660796        33
create_p-660979      33
send_p-660092        33
fail_p-660979_267    33
fail_p-660092_25     32
fail_p-660379_116    32
create_p-660796      32
deliver_p-660379     32
send_p-660874        32
send_p-660763        32
Name: object_count, dtype: int64

In [12]:
display(objects_per_event.describe())

count    21008.000000
mean         6.825257
std          5.426476
min          3.000000
25%          3.000000
50%          3.000000
75%         10.000000
max         37.000000
Name: object_count, dtype: float64

In [13]:
multi_object_events = objects_per_event[
    objects_per_event > 1
]

print(
    "Eventi associati a più di un oggetto:",
    len(multi_object_events),
)

Eventi associati a più di un oggetto: 21008

In [14]:
object_types_per_event = (
    ocel.relations
    .groupby("ocel:eid")["ocel:type"]
    .nunique()
    .rename("object_type_count")
    .sort_values(ascending=False)
)

multi_type_events = object_types_per_event[
    object_types_per_event > 1
]

print(
    "Eventi associati a più object type:",
    len(multi_type_events),
)

display(multi_type_events.head(20))

Eventi associati a più object type: 21008

ocel:eid
send_p-661097       4
send_p-661098       4
send_p-661099       4
send_p-661100       4
send_p-661101       4
send_p-661102       4
send_p-661103       4
send_p-661104       4
send_p-661105       4
send_p-661106       4
send_p-661107       4
send_p-661108       4
send_p-661109       4
send_p-661110       4
send_p-661111       4
send_p-661112       4
confirm_o-990017    4
confirm_o-990018    4
confirm_o-990019    4
confirm_o-990020    4
Name: object_type_count, dtype: int64

In [15]:
example_event_id = multi_type_events.index[0]

event_information = ocel.events[
    ocel.events["ocel:eid"] == example_event_id
]

event_relations = ocel.relations[
    ocel.relations["ocel:eid"] == example_event_id
]

display(event_information)
display(event_relations)

           ocel:eid            ocel:timestamp ocel:activity
1095  send_p-661097 2024-03-20 14:21:53+00:00  send package

,ocel:eid,ocel:oid,ocel:qualifier,ocel:activity,ocel:timestamp,ocel:type
133197,send_p-661097,Benedikt Knopp,forwarder,send package,2024-03-20 14:21:53+00:00,employees
133198,send_p-661097,Echo Dot,product,send package,2024-03-20 14:21:53+00:00,products
133199,send_p-661097,Echo Studio,product,send package,2024-03-20 14:21:53+00:00,products
133200,send_p-661097,Eduardo Goulart Rocha,shipper,send package,2024-03-20 14:21:53+00:00,employees
133201,send_p-661097,Fire Stick,product,send package,2024-03-20 14:21:53+00:00,products
133202,send_p-661097,MacBook Pro,product,send package,2024-03-20 14:21:53+00:00,products
133203,send_p-661097,i-887517,item,send package,2024-03-20 14:21:53+00:00,items
133204,send_p-661097,i-887518,item,send package,2024-03-20 14:21:53+00:00,items
133205,send_p-661097,i-887519,item,send package,2024-03-20 14:21:53+00:00,items
133206,send_p-661097,i-887520,item,send package,2024-03-20 14:21:53+00:00,items
133207,send_p-661097,i-887577,item,send package,2024-03-20 14:21:53+00:00,items
133208,send_p-661097,iPad,product,send package,2024-03-20 14:21:53+00:00,products
133209,send_p-661097,p-661097,shipped package,send package,2024-03-20 14:21:53+00:00,packages

In [16]:
activities_by_object_type = (
    pm4py.ocel_object_type_activities(ocel)
)

for object_type, activities in activities_by_object_type.items():
    print(f"\n{object_type}")
    for activity in sorted(activities):
        print(" -", activity)

employees
 - confirm order
 - create package
 - failed delivery
 - item out of stock
 - package delivered
 - pick item
 - reorder item
 - send package

items
 - confirm order
 - create package
 - failed delivery
 - item out of stock
 - package delivered
 - pay order
 - payment reminder
 - pick item
 - place order
 - reorder item
 - send package

orders
 - confirm order
 - pay order
 - payment reminder
 - place order

products
 - confirm order
 - create package
 - failed delivery
 - item out of stock
 - package delivered
 - pay order
 - payment reminder
 - pick item
 - place order
 - reorder item
 - send package

packages
 - create package
 - failed delivery
 - package delivered
 - send package

## Conclusioni

Il dataset **Order Management** è un log object-centric in formato OCEL 2.0
contenente **21.008 eventi**, **10.825 oggetti** e **143.463 relazioni
evento-oggetto**.

Sono presenti 11 attività e 5 tipi di oggetto:

- `orders`;
- `items`;
- `packages`;
- `products`;
- `employees`.

Tutti i 21.008 eventi sono associati a più di un oggetto e coinvolgono
più di un tipo di oggetto. Un singolo evento può essere collegato fino
a 37 oggetti.

Questi risultati confermano che il processo non può essere rappresentato
fedelmente mediante un solo case identifier tradizionale: uno stesso evento
può riguardare contemporaneamente ordini, articoli, prodotti, pacchi e
dipendenti.

La distribuzione degli oggetti è fortemente sbilanciata. In particolare,
il dataset contiene soltanto 20 prodotti e 18 dipendenti, riutilizzati
trasversalmente in numerosi eventi. Se tutti i tipi di oggetto vengono
considerati nella costruzione delle connected components, `products` ed
`employees` possono funzionare da ponti tra ordini differenti e unire
gran parte del log, o persino l'intero dataset, in un'unica process
execution.

Per questo motivo, nelle fasi successive sarà necessario confrontare
diversi criteri di estrazione delle process execution, evitando di
utilizzare indiscriminatamente tutti i tipi di oggetto. Una possibile
strategia consiste nell'impiegare un leading object type, come `orders`,
mantenendo comunque le relazioni object-centric necessarie alla costruzione
dell'instance graph.